name: Validate with hassfest

on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron:  "0 12 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
      - uses: "home-assistant/actions/hassfest@d56d093b9ab8d2105bc0cb6ee9bcc0ef4ec8b96d"
