name: Validate with hassfest

on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron:  "0 12 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v7"
      - uses: "home-assistant/actions/hassfest@a7c616ce81ccda50150bf1595786c71b1883fabb"
