name: Validate with hassfest

on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron:  "0 12 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
      - uses: "home-assistant/actions/hassfest@5f5b077d63a1e4c53019231409a0c4d791fb74e5"
